### ISSUE TITLE
Falta kustomization.yaml

### ISSUE THREAD

**Issue by Abuelodelanada** [achetronic/youtube#1]
Hola, gracias por tus videos!

Puede ser que falte el archivo `21-kubernetes_centraliza-los-logs-de-tu-cluster_loki-fluentd-y-grafana/004-hello-kubernetes/kustomization.yaml` ??

Estoy obteniendo:

```bash
$ kubectl apply -k .
error: unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory...
```

**Comment by achetronic** [comment]
Hola señor, muchas gracias por la corrección!

hay varios cambios en ese vídeo
El tema es que lo mudé todo de GitLab a GitHub y me faltó alguna cosa, así que:
- En ese directorio haz un **kubectl apply -f 001-hello-kubernetes.yaml**
- El directorio **003-log-it** no va a encontrar la imagen, que estaba en GitLab. Aunque es sólo de prueba, no deja de funcionar por ello

**Comment by achetronic** [comment]
I closed this issue because of the inactivity
